In [1]:
import numpy as np

Creating a Matrix using numpy

In [2]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,50,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 50 90]]


In [5]:
matrix_2.shape

(3, 3)

Creating Matrixes with Random Values

In [6]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.78093769 0.01430183 0.14654399]
 [0.15231912 0.33557409 0.33216659]
 [0.61481967 0.61059118 0.07422455]]


In [7]:
#creating matrix with random integers
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[61 58 85  8 45]
 [61 44 91 52 78]
 [99 44 88 46 80]
 [98 86 68 75 46]]


Matrix with all the values as 1

In [8]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [10]:
matrix_3 = np.ones((8,7), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


NUll Matrix or Zero Matrix

In [11]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
null_matrix = np.zeros((5,3), dtype=int)
print(null_matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


Identify Matrix

In [13]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
identity_matrix = np.eye(5,5),
print(identity_matrix)

(array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]]),)


Transpose of a Matrix

In [15]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[ 8 61 87 40 97]
 [29 57 34 13 26]
 [19 12 32 42 14]
 [ 1 65 43 18 82]]


In [16]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[ 8 29 19  1]
 [61 57 12 65]
 [87 34 32 43]
 [40 13 42 18]
 [97 26 14 82]]
