In [1]:
import numpy as np

Matrix Addition

Two Matrices can be added only if they have the same shape

In [2]:
# creating two matrices
A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [3]:
print(A)

[[2 3]
 [4 5]]


In [4]:
print(B)

[[6 7]
 [8 9]]


In [5]:
A.shape

(2, 2)

In [6]:
B.shape

(2, 2)

Adding two Matrixes

In [7]:
sum = A + B

In [8]:
print(sum)

[[ 8 10]
 [12 14]]


In [9]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [10]:
print(matrix_1)

[[7 0 9]
 [6 9 5]
 [5 0 7]]


In [11]:
print(matrix_2)

[[19  3 17]
 [ 5 17  2]
 [ 0  2 13]]


In [12]:
sum = np.add (matrix_1, matrix_2)

In [13]:
print(sum)

[[26  3 26]
 [11 26  7]
 [ 5  2 20]]


In [14]:
# create two matrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))

In [15]:
sum_2 = np.add(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

We get this error because shape of matrix_3 and matrix_4 are different

Matrix Subtraction

In [16]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [17]:
print(A)

[[2 3]
 [4 5]]


In [18]:
print(B)

[[6 7]
 [8 9]]


In [19]:
difference = A - B

In [20]:
print(difference)

[[-4 -4]
 [-4 -4]]


In [21]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [22]:
print(matrix_1)

[[2 7 4]
 [5 8 7]
 [5 9 1]]


In [23]:
print(matrix_2)

[[12  4  0]
 [ 3  4 16]
 [18  0 18]]


In [24]:
diff = np.subtract(matrix_1, matrix_2)

In [25]:
print(diff)

[[-10   3   4]
 [  2   4  -9]
 [-13   9 -17]]


Multiplying a matrix by a scalar

In [26]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[8 2 0 8]
 [7 8 7 9]
 [8 6 9 5]
 [0 5 3 2]]


In [27]:
product = np.multiply(x,y)

In [28]:
print(product)

[[40 10  0 40]
 [35 40 35 45]
 [40 30 45 25]
 [ 0 25 15 10]]


Multiplying 2 Matrices

In [29]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [30]:
print(matrix_3)

[[1 2 3]
 [3 3 3]
 [1 3 0]]


In [31]:
print(matrix_4)

[[1 3 0 4]
 [3 1 4 4]
 [4 2 2 2]]


In [33]:
product = np.dot(matrix_3, matrix_4)

In [34]:
print(product)

[[20  2 22 24]
 [ 8  4 14 12]
 [ 0  0  9  6]]


In [35]:
product.shape

(3, 4)

In [36]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(4,4))

In [37]:
product = np.dot(matrix_3, matrix_4)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

Element wise Matrix Multiplication

In [38]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [39]:
print(matrix_3)

[[4 3 1]
 [3 3 3]
 [3 0 0]]


In [40]:
print(matrix_4)

[[0 1 4]
 [1 0 1]
 [2 0 2]]


In [41]:
product = np.multiply(matrix_3, matrix_4)

In [42]:
print(product)

[[0 3 4]
 [3 0 3]
 [6 0 0]]


In [43]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [44]:
product = np.multiply(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 