# NumPy - Numerical Python


Advantages of Numpy Arrays:

  1. Allows several Mathematical Operations
  2. Faster operations

In [1]:
pip install numpy

     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.9 kB 165.2 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.9 kB 281.8 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 292.6 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 249.5 kB/s eta 0:00:00
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB 2.0 MB/s eta 0:00:09
   ---------------------------------------- 0.1/16.5 MB 1.3 MB/s eta 0:00:13
   ---------------------------------------- 0.1/16.5 MB 901.1 kB/s eta 0:00:19
    --------------------------------------- 0.2/16.5 MB 1.1 MB/s eta 0:00:15
    --------------------------------------- 0.3/16.5 MB 1.1 MB/s eta 0:00:15
    --------------------------------------- 0.4/16.5 MB 1.2 MB/s eta 0:00:14
 

In [2]:
import numpy as np

List vs Numpy - Time Taken

In [3]:
from time import process_time

Time taken by a list

In [4]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0


In [5]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0


Numpy Array

In [8]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Creating one directional array


In [9]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [10]:
a.shape

(4,)

Creating two-directional array


In [11]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
b.shape

(2, 4)

In [13]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [14]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [17]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.62341789 0.82333723 0.97818102 0.34494577]
 [0.25565473 0.32471423 0.57247059 0.22395689]
 [0.12505914 0.23262679 0.62693034 0.35704348]]


In [19]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[72 55 27 56 41]
 [58 78 12 94 64]
 [80 63 22 80 17]]


In [20]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [21]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [22]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

*Analysing* a numpy array

In [24]:
c = np.random.randint(10,90,(5,5))
print(c)

[[31 76 43 73 63]
 [82 12 17 45 67]
 [86 20 37 58 50]
 [29 38 52 48 82]
 [16 78 84 48 38]]


In [25]:
# array dimension
print(c.shape)

(5, 5)


In [26]:
# number of dimensions
print(c.ndim)

2


In [27]:
# number of elements in an array
print(c.size)

25


In [28]:
# checking the data type of the values in the array
print(c.dtype)

int32


Mathematical operations on a np array


In [29]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [30]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [31]:
print(a)
print(b)

[[1 6 1]
 [3 6 9]
 [4 5 3]]
[[18 10 16]
 [19 16 14]
 [16 15 10]]


In [32]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[19 16 17]
 [22 22 23]
 [20 20 13]]
[[-17  -4 -15]
 [-16 -10  -5]
 [-12 -10  -7]]
[[ 18  60  16]
 [ 57  96 126]
 [ 64  75  30]]
[[0.05555556 0.6        0.0625    ]
 [0.15789474 0.375      0.64285714]
 [0.25       0.33333333 0.3       ]]


In [33]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [34]:
print(a)
print(b)

[[6 4 3]
 [5 0 4]
 [6 6 5]]
[[15 17 14]
 [13 12 10]
 [19 15 16]]


In [35]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[21 21 17]
 [18 12 14]
 [25 21 21]]
[[ -9 -13 -11]
 [ -8 -12  -6]
 [-13  -9 -11]]
[[ 90  68  42]
 [ 65   0  40]
 [114  90  80]]
[[0.4        0.23529412 0.21428571]
 [0.38461538 0.         0.4       ]
 [0.31578947 0.4        0.3125    ]]


Array Manipulation

In [36]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 3 7]
 [2 6 6]]
(2, 3)


In [37]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 2]
 [3 6]
 [7 6]]
(3, 2)


In [38]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 1 8]
 [5 7 6]]
(2, 3)


In [39]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[7 5]
 [1 7]
 [8 6]]
(3, 2)


In [40]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 2 3]
 [0 1 9]]
(2, 3)


In [41]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 2]
 [3 0]
 [1 9]]
(3, 2)
